on: issue_comment

jobs:
  spray_happiness:
    name: Spray happiness
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'User commented: ${{ github.event.comment.body }}'
      - name: Create happiness comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          big_secret: ${{ secrets.BIG_SECRET }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Wow, much happiness--all for you!
