on: issue_comment

jobs:
  spray_happiness:
    name: Spray happiness
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'User commented: ${{ github.event.comment.body }}'
      - run: |
          echo "BIG_SECRET=${{ secrets.BIG_SECRET }}" >> $GITHUB_ENV
      - name: Create happiness comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Wow, much happiness--all for you!
